name: API Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch: 

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Set up .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build the project
      - name: Build
        run: dotnet build --no-restore

      # Step 5: Run the API server in the background
      - name: Run API Server
        run: |
          dotnet run --project keasocial/keasocial.csproj --urls http://localhost:5260 &
        env:
          ASPNETCORE_URLS: http://localhost:5260
          continue-on-error: true 
      # Step 6: Set up Node.js for Newman
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 7: Install Newman
      - name: Install Newman
        run: npm install -g newman

      # Step 8: Run Postman Collection with Newman
      - name: Run API Tests
        run: |
          newman run keasocial.Tests/postman/Keasocial.postman_collection.json \
          --environment keasocial.Tests/postman/keasocial.postman_environment.json \
          --reporters cli,junit \
          --reporter-junit-export TestResults/newman-api-tests.xml

      # Step 9: Upload API Test Results
      - name: Upload API Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: api-test-results
          path: TestResults/newman-api-tests.xml