name: API Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  workflow_dispatch: 

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js for Newman
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install Newman
      - name: Install Newman
        run: npm install -g newman

      # Step 4: Run Postman Collection with Newman
      - name: Run API Tests
        run: |
          newman run postman/Keasocial.postman_collection.json \
          --environment postman/keasocial.postman_environment.json \
          --reporters cli,junit \
          --reporter-junit-export TestResults/newman-api-tests.xml

      # Step 5: Upload API Test Results
      - name: Upload API Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: api-test-results
          path: TestResults/newman-api-tests.xml