name: Continuous Integration KeaSocial

on:
    push:
        branches: ["integration_test_ci"]
    pull_request:
        branches: ["integration_test_ci"]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        env:
            ASPNETCORE_ENVIRONMENT: Testing

        steps:
            # Step 1: Check out the code
            - uses: actions/checkout@v4

            # Step 2: Set up .NET
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 8.0.x

            - name: Create appsettings.json
              run: |
                  echo '{
                    "Logging": {
                      "LogLevel": {
                        "Default": "Information",
                        "Microsoft.AspNetCore": "Warning"
                      }
                    },
                    "ConnectionStrings": {
                      "WeatherApiConnection": "${{ secrets.WEATHER_API_KEY }}"
                    },
                    "Jwt": {
                      "Key": "${{ secrets.JWT_KEY }}",
                      "Issuer": "https://localhost:5000/",
                      "Audience": "keasocial"
                    }
                  }' > appsettings.json

            # Step 3: Restore dependencies
            - name: Restore dependencies
              run: dotnet restore

            # Step 6: Build the project
            - name: Build
              run: dotnet build --no-restore

            - name: Run Tests with Debugging
              run: |
                  dotnet test --logger "console;verbosity=detailed"
                  cat test-logs/*.log

            # Step 9: Upload Code Coverage Report
            - name: Upload Coverage Report
              if: always()
              uses: actions/upload-artifact@v3
              with:
                  name: code-coverage-report
                  path: TestResults/**/coverage.opencover.xml
