name: Continuous Integration with SonarCloud

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Check out the code
            - uses: actions/checkout@v4

            # Step 2: Set up .NET
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "8.0.x"

            # Step 3: Install SonarCloud Scanner
            - name: Install SonarCloud Scanner
              run: dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner

            # Step 4: Begin SonarCloud Analysis
            - name: SonarCloud Begin
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              run: |
                  ./.sonar/scanner/dotnet-sonarscanner begin \
                    /k:"kristianhadberg_keasocial" \
                    /o:"kristianhadberg" \
                    /d:sonar.host.url="https://sonarcloud.io" \
                    /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
                    /d:sonar.cs.opencover.reportsPaths="**/TestResults/*/coverage.opencover.xml"

            # Step 5: Build the Project
            - name: Build
              run: dotnet build --no-restore

            # Step 6: Run Tests with Coverage
            - name: Test with Coverage
              run: dotnet test --collect:"XPlat Code Coverage" --verbosity normal

            # Step 7: End SonarCloud Analysis
            - name: SonarCloud End
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              run: ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
